// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: bigmap.proto

package bigmap

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//消息号
type MSG_BIGMAP int32

const (
	MSG_BIGMAP_PLACEHOLDER_MAP MSG_BIGMAP = 0 //占位
	//账号模块
	MSG_BIGMAP_Module_BIGMAP MSG_BIGMAP = 2000
	//模块信息
	MSG_BIGMAP_C2S_GetMapInfo MSG_BIGMAP = 2001 //
)

// Enum value maps for MSG_BIGMAP.
var (
	MSG_BIGMAP_name = map[int32]string{
		0:    "PLACEHOLDER_MAP",
		2000: "Module_BIGMAP",
		2001: "C2S_GetMapInfo",
	}
	MSG_BIGMAP_value = map[string]int32{
		"PLACEHOLDER_MAP": 0,
		"Module_BIGMAP":   2000,
		"C2S_GetMapInfo":  2001,
	}
)

func (x MSG_BIGMAP) Enum() *MSG_BIGMAP {
	p := new(MSG_BIGMAP)
	*p = x
	return p
}

func (x MSG_BIGMAP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_BIGMAP) Descriptor() protoreflect.EnumDescriptor {
	return file_bigmap_proto_enumTypes[0].Descriptor()
}

func (MSG_BIGMAP) Type() protoreflect.EnumType {
	return &file_bigmap_proto_enumTypes[0]
}

func (x MSG_BIGMAP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG_BIGMAP.Descriptor instead.
func (MSG_BIGMAP) EnumDescriptor() ([]byte, []int) {
	return file_bigmap_proto_rawDescGZIP(), []int{0}
}

//地图信息
type P_MapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *P_MapInfo) Reset() {
	*x = P_MapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bigmap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P_MapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_MapInfo) ProtoMessage() {}

func (x *P_MapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bigmap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_MapInfo.ProtoReflect.Descriptor instead.
func (*P_MapInfo) Descriptor() ([]byte, []int) {
	return file_bigmap_proto_rawDescGZIP(), []int{0}
}

//获取地图信息
type C2S_GetMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_GetMapInfo) Reset() {
	*x = C2S_GetMapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bigmap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_GetMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_GetMapInfo) ProtoMessage() {}

func (x *C2S_GetMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bigmap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_GetMapInfo.ProtoReflect.Descriptor instead.
func (*C2S_GetMapInfo) Descriptor() ([]byte, []int) {
	return file_bigmap_proto_rawDescGZIP(), []int{1}
}

type S2C_GetMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_GetMapInfo) Reset() {
	*x = S2C_GetMapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bigmap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_GetMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GetMapInfo) ProtoMessage() {}

func (x *S2C_GetMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bigmap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GetMapInfo.ProtoReflect.Descriptor instead.
func (*S2C_GetMapInfo) Descriptor() ([]byte, []int) {
	return file_bigmap_proto_rawDescGZIP(), []int{2}
}

//移动
type C2S_Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_Move) Reset() {
	*x = C2S_Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bigmap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Move) ProtoMessage() {}

func (x *C2S_Move) ProtoReflect() protoreflect.Message {
	mi := &file_bigmap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Move.ProtoReflect.Descriptor instead.
func (*C2S_Move) Descriptor() ([]byte, []int) {
	return file_bigmap_proto_rawDescGZIP(), []int{3}
}

type S2C_Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_Move) Reset() {
	*x = S2C_Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bigmap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Move) ProtoMessage() {}

func (x *S2C_Move) ProtoReflect() protoreflect.Message {
	mi := &file_bigmap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Move.ProtoReflect.Descriptor instead.
func (*S2C_Move) Descriptor() ([]byte, []int) {
	return file_bigmap_proto_rawDescGZIP(), []int{4}
}

var File_bigmap_proto protoreflect.FileDescriptor

var file_bigmap_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x69, 0x67, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0b,
	0x0a, 0x09, 0x50, 0x5f, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x63,
	0x32, 0x73, 0x5f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x10, 0x0a,
	0x0e, 0x73, 0x32, 0x63, 0x5f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x0a, 0x0a, 0x08, 0x63, 0x32, 0x73, 0x5f, 0x4d, 0x6f, 0x76, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x73,
	0x32, 0x63, 0x5f, 0x4d, 0x6f, 0x76, 0x65, 0x2a, 0x4a, 0x0a, 0x0a, 0x4d, 0x53, 0x47, 0x5f, 0x42,
	0x49, 0x47, 0x4d, 0x41, 0x50, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x48, 0x4f,
	0x4c, 0x44, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x50, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0d, 0x4d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x5f, 0x42, 0x49, 0x47, 0x4d, 0x41, 0x50, 0x10, 0xd0, 0x0f, 0x12, 0x13,
	0x0a, 0x0e, 0x43, 0x32, 0x53, 0x5f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x10, 0xd1, 0x0f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bigmap_proto_rawDescOnce sync.Once
	file_bigmap_proto_rawDescData = file_bigmap_proto_rawDesc
)

func file_bigmap_proto_rawDescGZIP() []byte {
	file_bigmap_proto_rawDescOnce.Do(func() {
		file_bigmap_proto_rawDescData = protoimpl.X.CompressGZIP(file_bigmap_proto_rawDescData)
	})
	return file_bigmap_proto_rawDescData
}

var file_bigmap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bigmap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bigmap_proto_goTypes = []interface{}{
	(MSG_BIGMAP)(0),        // 0: MSG_BIGMAP
	(*P_MapInfo)(nil),      // 1: P_MapInfo
	(*C2S_GetMapInfo)(nil), // 2: c2s_GetMapInfo
	(*S2C_GetMapInfo)(nil), // 3: s2c_GetMapInfo
	(*C2S_Move)(nil),       // 4: c2s_Move
	(*S2C_Move)(nil),       // 5: s2c_Move
}
var file_bigmap_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bigmap_proto_init() }
func file_bigmap_proto_init() {
	if File_bigmap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bigmap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P_MapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bigmap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_GetMapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bigmap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_GetMapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bigmap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bigmap_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bigmap_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bigmap_proto_goTypes,
		DependencyIndexes: file_bigmap_proto_depIdxs,
		EnumInfos:         file_bigmap_proto_enumTypes,
		MessageInfos:      file_bigmap_proto_msgTypes,
	}.Build()
	File_bigmap_proto = out.File
	file_bigmap_proto_rawDesc = nil
	file_bigmap_proto_goTypes = nil
	file_bigmap_proto_depIdxs = nil
}
