// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: account.proto

package account

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//消息号
type MSG_ACCOUNT int32

const (
	MSG_ACCOUNT_PLACEHOLDER MSG_ACCOUNT = 0 //占位
	//账号模块
	MSG_ACCOUNT_Module MSG_ACCOUNT = 1000
	//method
	MSG_ACCOUNT_C2S_Login          MSG_ACCOUNT = 1001 //用户登陆
	MSG_ACCOUNT_S2C_Login          MSG_ACCOUNT = 1002
	MSG_ACCOUNT_C2S_CreateRole     MSG_ACCOUNT = 1003 //创建角色
	MSG_ACCOUNT_S2C_CreateRole     MSG_ACCOUNT = 1004
	MSG_ACCOUNT_C2S_UpdateRoleName MSG_ACCOUNT = 1005 //修改角色名
	MSG_ACCOUNT_S2C_UpdateRoleName MSG_ACCOUNT = 1006
	MSG_ACCOUNT_S2C_RoleAddExp     MSG_ACCOUNT = 1010 //角色获取经验
)

// Enum value maps for MSG_ACCOUNT.
var (
	MSG_ACCOUNT_name = map[int32]string{
		0:    "PLACEHOLDER",
		1000: "Module",
		1001: "C2S_Login",
		1002: "S2C_Login",
		1003: "C2S_CreateRole",
		1004: "S2C_CreateRole",
		1005: "C2S_UpdateRoleName",
		1006: "S2C_UpdateRoleName",
		1010: "S2C_RoleAddExp",
	}
	MSG_ACCOUNT_value = map[string]int32{
		"PLACEHOLDER":        0,
		"Module":             1000,
		"C2S_Login":          1001,
		"S2C_Login":          1002,
		"C2S_CreateRole":     1003,
		"S2C_CreateRole":     1004,
		"C2S_UpdateRoleName": 1005,
		"S2C_UpdateRoleName": 1006,
		"S2C_RoleAddExp":     1010,
	}
)

func (x MSG_ACCOUNT) Enum() *MSG_ACCOUNT {
	p := new(MSG_ACCOUNT)
	*p = x
	return p
}

func (x MSG_ACCOUNT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_ACCOUNT) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[0].Descriptor()
}

func (MSG_ACCOUNT) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[0]
}

func (x MSG_ACCOUNT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG_ACCOUNT.Descriptor instead.
func (MSG_ACCOUNT) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

//用户游戏信息
type P_RoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleID        int32           `protobuf:"varint,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	RoleName      string          `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	Exp           int64           `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Level         int32           `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Country       int32           `protobuf:"varint,5,opt,name=country,proto3" json:"country,omitempty"`                                                                                                      //所属国家
	TesourcesList map[int32]int32 `protobuf:"bytes,6,rep,name=TesourcesList,proto3" json:"TesourcesList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //玩家资源列表
	Settings      *RoleSettings   `protobuf:"bytes,7,opt,name=Settings,proto3" json:"Settings,omitempty"`                                                                                                     //游戏内设置
}

func (x *P_RoleInfo) Reset() {
	*x = P_RoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P_RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P_RoleInfo) ProtoMessage() {}

func (x *P_RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P_RoleInfo.ProtoReflect.Descriptor instead.
func (*P_RoleInfo) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *P_RoleInfo) GetRoleID() int32 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *P_RoleInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *P_RoleInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *P_RoleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *P_RoleInfo) GetCountry() int32 {
	if x != nil {
		return x.Country
	}
	return 0
}

func (x *P_RoleInfo) GetTesourcesList() map[int32]int32 {
	if x != nil {
		return x.TesourcesList
	}
	return nil
}

func (x *P_RoleInfo) GetSettings() *RoleSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

//游戏设置
type RoleSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoSelectTactics bool `protobuf:"varint,1,opt,name=AutoSelectTactics,proto3" json:"AutoSelectTactics,omitempty"` //自动选择战术
}

func (x *RoleSettings) Reset() {
	*x = RoleSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSettings) ProtoMessage() {}

func (x *RoleSettings) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSettings.ProtoReflect.Descriptor instead.
func (*RoleSettings) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *RoleSettings) GetAutoSelectTactics() bool {
	if x != nil {
		return x.AutoSelectTactics
	}
	return false
}

//用户登陆
type C2S_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *C2S_Login) Reset() {
	*x = C2S_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Login) ProtoMessage() {}

func (x *C2S_Login) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Login.ProtoReflect.Descriptor instead.
func (*C2S_Login) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_Login) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *C2S_Login) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type S2C_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg      string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RoleInfo *P_RoleInfo `protobuf:"bytes,3,opt,name=RoleInfo,proto3" json:"RoleInfo,omitempty"`
}

func (x *S2C_Login) Reset() {
	*x = S2C_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Login) ProtoMessage() {}

func (x *S2C_Login) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Login.ProtoReflect.Descriptor instead.
func (*S2C_Login) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_Login) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *S2C_Login) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *S2C_Login) GetRoleInfo() *P_RoleInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

// 创建角色
type C2S_CreateRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName string `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	Country  int32  `protobuf:"varint,2,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *C2S_CreateRole) Reset() {
	*x = C2S_CreateRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_CreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CreateRole) ProtoMessage() {}

func (x *C2S_CreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CreateRole.ProtoReflect.Descriptor instead.
func (*C2S_CreateRole) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_CreateRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *C2S_CreateRole) GetCountry() int32 {
	if x != nil {
		return x.Country
	}
	return 0
}

type S2C_CreateRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Roleid  int32  `protobuf:"varint,3,opt,name=roleid,proto3" json:"roleid,omitempty"`
}

func (x *S2C_CreateRole) Reset() {
	*x = S2C_CreateRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_CreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CreateRole) ProtoMessage() {}

func (x *S2C_CreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CreateRole.ProtoReflect.Descriptor instead.
func (*S2C_CreateRole) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_CreateRole) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *S2C_CreateRole) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *S2C_CreateRole) GetRoleid() int32 {
	if x != nil {
		return x.Roleid
	}
	return 0
}

// 修改角色名
type C2S_UpdateRoleName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateName string `protobuf:"bytes,1,opt,name=UpdateName,proto3" json:"UpdateName,omitempty"`
}

func (x *C2S_UpdateRoleName) Reset() {
	*x = C2S_UpdateRoleName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_UpdateRoleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_UpdateRoleName) ProtoMessage() {}

func (x *C2S_UpdateRoleName) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_UpdateRoleName.ProtoReflect.Descriptor instead.
func (*C2S_UpdateRoleName) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_UpdateRoleName) GetUpdateName() string {
	if x != nil {
		return x.UpdateName
	}
	return ""
}

type S2C_UpdateRoleName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *S2C_UpdateRoleName) Reset() {
	*x = S2C_UpdateRoleName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_UpdateRoleName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_UpdateRoleName) ProtoMessage() {}

func (x *S2C_UpdateRoleName) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_UpdateRoleName.ProtoReflect.Descriptor instead.
func (*S2C_UpdateRoleName) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_UpdateRoleName) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *S2C_UpdateRoleName) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type S2C_RoleAddExp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddExp   int64 `protobuf:"varint,1,opt,name=addExp,proto3" json:"addExp,omitempty"`
	NewExp   int64 `protobuf:"varint,2,opt,name=NewExp,proto3" json:"NewExp,omitempty"`
	NewLevel int64 `protobuf:"varint,3,opt,name=NewLevel,proto3" json:"NewLevel,omitempty"`
}

func (x *S2C_RoleAddExp) Reset() {
	*x = S2C_RoleAddExp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RoleAddExp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RoleAddExp) ProtoMessage() {}

func (x *S2C_RoleAddExp) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RoleAddExp.ProtoReflect.Descriptor instead.
func (*S2C_RoleAddExp) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_RoleAddExp) GetAddExp() int64 {
	if x != nil {
		return x.AddExp
	}
	return 0
}

func (x *S2C_RoleAddExp) GetNewExp() int64 {
	if x != nil {
		return x.NewExp
	}
	return 0
}

func (x *S2C_RoleAddExp) GetNewLevel() int64 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

var File_account_proto protoreflect.FileDescriptor

var file_account_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc5, 0x02, 0x0a, 0x0a, 0x50, 0x5f, 0x52,
	0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x4c, 0x0a,
	0x0d, 0x54, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x50,
	0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x54, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x1a, 0x40,
	0x0a, 0x12, 0x54, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x3c, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x2c, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x6f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x61,
	0x63, 0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x41, 0x75, 0x74,
	0x6f, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x54, 0x61, 0x63, 0x74, 0x69, 0x63, 0x73, 0x22, 0x41,
	0x0a, 0x09, 0x63, 0x32, 0x73, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x22, 0x68, 0x0a, 0x09, 0x73, 0x32, 0x63, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2f, 0x0a, 0x08, 0x52, 0x6f,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x50, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x46, 0x0a, 0x0e, 0x63,
	0x32, 0x73, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x22, 0x54, 0x0a, 0x0e, 0x73, 0x32, 0x63, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x12, 0x63, 0x32, 0x73,
	0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x40, 0x0a, 0x12, 0x73, 0x32, 0x63, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x5c, 0x0a, 0x0e, 0x73, 0x32, 0x63, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x64, 0x64,
	0x45, 0x78, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x64, 0x64, 0x45, 0x78, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x64, 0x64, 0x45, 0x78, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x4e,
	0x65, 0x77, 0x45, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4e, 0x65, 0x77,
	0x45, 0x78, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4e, 0x65, 0x77, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x2a,
	0xbc, 0x01, 0x0a, 0x0b, 0x4d, 0x53, 0x47, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x12,
	0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x45, 0x52, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x10, 0xe8, 0x07, 0x12, 0x0e, 0x0a,
	0x09, 0x43, 0x32, 0x53, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0xe9, 0x07, 0x12, 0x0e, 0x0a,
	0x09, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0xea, 0x07, 0x12, 0x13, 0x0a,
	0x0e, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x10,
	0xeb, 0x07, 0x12, 0x13, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x10, 0xec, 0x07, 0x12, 0x17, 0x0a, 0x12, 0x43, 0x32, 0x53, 0x5f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x10, 0xed, 0x07,
	0x12, 0x17, 0x0a, 0x12, 0x53, 0x32, 0x43, 0x5f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x10, 0xee, 0x07, 0x12, 0x13, 0x0a, 0x0e, 0x53, 0x32, 0x43,
	0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x64, 0x64, 0x45, 0x78, 0x70, 0x10, 0xf2, 0x07, 0x42, 0x1c,
	0x5a, 0x1a, 0x73, 0x6c, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x73, 0x67, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData = file_account_proto_rawDesc
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_proto_rawDescData)
	})
	return file_account_proto_rawDescData
}

var file_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_account_proto_goTypes = []interface{}{
	(MSG_ACCOUNT)(0),           // 0: account.MSG_ACCOUNT
	(*P_RoleInfo)(nil),         // 1: account.P_RoleInfo
	(*RoleSettings)(nil),       // 2: account.RoleSettings
	(*C2S_Login)(nil),          // 3: account.c2s_Login
	(*S2C_Login)(nil),          // 4: account.s2c_Login
	(*C2S_CreateRole)(nil),     // 5: account.c2s_CreateRole
	(*S2C_CreateRole)(nil),     // 6: account.s2c_CreateRole
	(*C2S_UpdateRoleName)(nil), // 7: account.c2s_UpdateRoleName
	(*S2C_UpdateRoleName)(nil), // 8: account.s2c_UpdateRoleName
	(*S2C_RoleAddExp)(nil),     // 9: account.s2c_RoleAddExp
	nil,                        // 10: account.P_RoleInfo.TesourcesListEntry
}
var file_account_proto_depIdxs = []int32{
	10, // 0: account.P_RoleInfo.TesourcesList:type_name -> account.P_RoleInfo.TesourcesListEntry
	2,  // 1: account.P_RoleInfo.Settings:type_name -> account.RoleSettings
	1,  // 2: account.s2c_Login.RoleInfo:type_name -> account.P_RoleInfo
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P_RoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_CreateRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_CreateRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_UpdateRoleName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_UpdateRoleName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_RoleAddExp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		EnumInfos:         file_account_proto_enumTypes,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_rawDesc = nil
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
