// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkMsg struct {
	Module               int32    `protobuf:"varint,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Method               int32    `protobuf:"varint,2,opt,name=Method,proto3" json:"Method,omitempty"`
	MsgBytes             []byte   `protobuf:"bytes,3,opt,name=MsgBytes,proto3" json:"MsgBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkMsg) Reset()         { *m = NetworkMsg{} }
func (m *NetworkMsg) String() string { return proto.CompactTextString(m) }
func (*NetworkMsg) ProtoMessage()    {}
func (*NetworkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *NetworkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkMsg.Unmarshal(m, b)
}
func (m *NetworkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkMsg.Marshal(b, m, deterministic)
}
func (m *NetworkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkMsg.Merge(m, src)
}
func (m *NetworkMsg) XXX_Size() int {
	return xxx_messageInfo_NetworkMsg.Size(m)
}
func (m *NetworkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkMsg proto.InternalMessageInfo

func (m *NetworkMsg) GetModule() int32 {
	if m != nil {
		return m.Module
	}
	return 0
}

func (m *NetworkMsg) GetMethod() int32 {
	if m != nil {
		return m.Method
	}
	return 0
}

func (m *NetworkMsg) GetMsgBytes() []byte {
	if m != nil {
		return m.MsgBytes
	}
	return nil
}

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=PageNumber,proto3" json:"PageNumber,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=ResultPerPage,proto3" json:"ResultPerPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type UserLoginTos struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginTos) Reset()         { *m = UserLoginTos{} }
func (m *UserLoginTos) String() string { return proto.CompactTextString(m) }
func (*UserLoginTos) ProtoMessage()    {}
func (*UserLoginTos) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *UserLoginTos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginTos.Unmarshal(m, b)
}
func (m *UserLoginTos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginTos.Marshal(b, m, deterministic)
}
func (m *UserLoginTos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginTos.Merge(m, src)
}
func (m *UserLoginTos) XXX_Size() int {
	return xxx_messageInfo_UserLoginTos.Size(m)
}
func (m *UserLoginTos) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginTos.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginTos proto.InternalMessageInfo

func (m *UserLoginTos) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserLoginTos) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type UserLoginToc struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginToc) Reset()         { *m = UserLoginToc{} }
func (m *UserLoginToc) String() string { return proto.CompactTextString(m) }
func (*UserLoginToc) ProtoMessage()    {}
func (*UserLoginToc) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *UserLoginToc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginToc.Unmarshal(m, b)
}
func (m *UserLoginToc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginToc.Marshal(b, m, deterministic)
}
func (m *UserLoginToc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginToc.Merge(m, src)
}
func (m *UserLoginToc) XXX_Size() int {
	return xxx_messageInfo_UserLoginToc.Size(m)
}
func (m *UserLoginToc) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginToc.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginToc proto.InternalMessageInfo

func (m *UserLoginToc) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserLoginToc) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*NetworkMsg)(nil), "NetworkMsg")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*UserLoginTos)(nil), "UserLogin_tos")
	proto.RegisterType((*UserLoginToc)(nil), "UserLogin_toc")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0x47, 0xa9, 0xa3, 0xb3, 0xfd, 0xb0, 0x20, 0x41, 0xa4, 0x28, 0xc8, 0x28, 0x1e, 0x76, 0xf2,
	0xe2, 0xd1, 0xdb, 0xce, 0xb6, 0xcc, 0x88, 0xe0, 0x6d, 0x74, 0xed, 0x8f, 0x6c, 0x6c, 0x69, 0x34,
	0x5f, 0x82, 0xee, 0xbf, 0x97, 0x66, 0x51, 0xdc, 0x2d, 0xef, 0x41, 0xde, 0x2f, 0x84, 0x72, 0xcd,
	0xea, 0xe1, 0xc3, 0x1a, 0x67, 0xaa, 0x77, 0xa2, 0x06, 0xee, 0xcb, 0xd8, 0x5d, 0xcd, 0x4a, 0x5c,
	0xd3, 0xb4, 0x36, 0xbd, 0xdf, 0xa3, 0x4c, 0x66, 0xc9, 0x3c, 0x95, 0x91, 0x82, 0x87, 0xdb, 0x98,
	0xbe, 0x3c, 0x8b, 0x3e, 0x90, 0xb8, 0xa1, 0xac, 0x66, 0xb5, 0x38, 0x38, 0x70, 0x39, 0x99, 0x25,
	0xf3, 0x0b, 0xf9, 0xc7, 0xd5, 0x8e, 0x8a, 0x57, 0xb4, 0xb6, 0xdb, 0x48, 0x7c, 0x7a, 0xb0, 0x13,
	0x57, 0x94, 0xbe, 0x78, 0xd8, 0x43, 0x68, 0xe7, 0xf2, 0x08, 0xe2, 0x8e, 0x68, 0xd9, 0x2a, 0x34,
	0x5e, 0xaf, 0x61, 0x63, 0xfe, 0x9f, 0x11, 0xf7, 0x54, 0x48, 0xb0, 0xdf, 0xbb, 0x25, 0xec, 0xa8,
	0xc3, 0x4e, 0x2a, 0x4f, 0x65, 0xb5, 0xa0, 0xe2, 0x8d, 0x61, 0x9f, 0x8d, 0xda, 0x0e, 0x2b, 0x67,
	0x58, 0xdc, 0x52, 0xee, 0x19, 0x76, 0x35, 0xb4, 0x1a, 0x71, 0x30, 0x1b, 0x45, 0xd3, 0x6a, 0x8c,
	0x2f, 0xd9, 0x0e, 0x3d, 0xbe, 0xe3, 0xdc, 0x11, 0xaa, 0xa7, 0xd3, 0x46, 0x27, 0x4a, 0x3a, 0x67,
	0xdf, 0x75, 0x60, 0x0e, 0x85, 0x4c, 0xfe, 0xa2, 0xb8, 0xa4, 0x89, 0x66, 0x15, 0xae, 0xe7, 0x72,
	0x3c, 0xae, 0xa7, 0xe1, 0x3b, 0x1f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xf3, 0x8c, 0xc9,
	0x5b, 0x01, 0x00, 0x00,
}
